import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/context/Provider";
import NavComponent from "@/components/navComponent/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CourseSavers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          {children}

          <footer>
            <NavComponent />
          </footer>
        </body>
      </html>
    </Provider>
  );
}
