'use client'

import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "@/context/Provider"
import NavComponent from "@/components/navComponent/page";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CourseSavers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  // const router = useRouter();
  // const showNav = router.pathname !== '/';

  return (
    <Provider>
      <html lang="en">
        <body className={inter.className}>
          {children}
          {/* {showNav && ( */}
          <footer>
            <NavComponent />
          </footer>
          {/* )} */}
        </body>
      </html>
    </Provider>
  );
}
