import "./globals.css";
import { Inter } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CourseSavers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        signIn: {
          elements: {
            formButtonPrimary: {
              color: '#FFFFFF',
              backgroundColor: '#8541CB'
            },
            headerTitle: 'text-center',
            headerSubtitle: 'hidden',
            footer: 'flex justify-center',
            card: 'bg-[transparent] mb-0',
            formFieldLabel: 'hidden',
            formFieldInput: 'bg-[#F9F9F9]'
          },
          variables: {
            
          }
        },
        signUp: {
          elements: {
            formButtonPrimary: {
              color: '#FFFFFF',
              backgroundColor: '#8541CB'
            },
            headerTitle: 'text-center',
            headerSubtitle: 'hidden',
            footer: 'flex justify-center'
          }
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
